# Relaxed.Ruby.Style

AllCops:
  Exclude:
    - '*.gemspec'
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
    - 'Rakefile'
  TargetRubyVersion: 2.4

inherit_from: 'https://relaxed.ruby.style/rubocop.yml'

# Sometimes I believe this reads better
# This also causes spacing issues on multi-line fixes
Style/BracesAroundHashParameters:
  Enabled: false

# We use class vars and will have to continue doing so for compatability
Style/ClassVars:
  Enabled: false

# We need these names for backwards compatability
Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# This has been used for customization
Style/MutableConstant:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Performance/Count:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

# We can use good judgement here
Style/RegexpLiteral:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/AlignHash:
  Enabled: false

# Symbol Arrays are ok and the %i syntax widely unknown
Style/SymbolArray:
  Enabled: false

# Rails/DynamicFindBy:
#   Whitelist:
#     - find_by_param
#     - find_by_param!

# We use a lot of
#
#     expect {
#       something
#     }.to { happen }
#
# syntax in the specs files.
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '*/spec/**/*'
    - 'spec/**/*' # For the benefit of apps that inherit from this config

# We use eval to add common_spree_dependencies into the Gemfiles of each of our gems
Security/Eval:
  Exclude:
    - 'Gemfile'
    - 'common_spree_dependencies.rb'
    - '*/Gemfile'

Naming/VariableNumber:
  Enabled: false

# Write empty methods as you wish.
Style/EmptyMethod:
  Enabled: false
